# Generated by Django 5.2.3 on 2026-03-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city_area', models.CharField(max_length=200)),
                ('industry_domains_list', models.JSONField(blank=True, default=list)),
                ('finance_exposure', models.JSONField(blank=True, default=list)),
                ('hiring_type', models.CharField(blank=True, max_length=100)),
                ('work_model', models.CharField(blank=True, max_length=50)),
                ('jobs_available', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('ca_hiring', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(max_length=50, verbose_name='ICAI Firm Reg No')),
                ('partner_details', models.TextField()),
                ('city_area', models.CharField(max_length=100)),
                ('no_of_partners', models.PositiveIntegerField()),
                ('no_of_paid_assistants', models.PositiveIntegerField()),
                ('articleship_positions', models.PositiveIntegerField(default=0)),
                ('jobs_available', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=200)),
                ('exposure_level', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Routine', 'Routine')], max_length=10)),
                ('work_hours', models.CharField(choices=[('Fixed', 'Fixed'), ('Seasonal', 'Seasonal Extended')], max_length=20)),
                ('stipend_range', models.CharField(max_length=100)),
                ('leave_policy', models.TextField()),
                ('mentorship_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
