# Generated by Django 5.2.4 on 2026-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='domain',
        ),
        migrations.AddField(
            model_name='job',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='adminpanel.domain'),
        ),
    ]
