# Generated by Django 5.2.4 on 2026-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_domain_job_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_skill_match',
            field=models.IntegerField(default=0),
        ),
    ]
