# Generated by Django 5.2.3 on 2026-03-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(choices=[('Statutory Audit', 'Statutory Audit'), ('Internal Audit', 'Internal Audit'), ('Tax Audit', 'Tax Audit'), ('GST Compliance', 'GST Compliance'), ('Income Tax Returns', 'Income Tax Returns'), ('TDS Returns', 'TDS Returns'), ('ROC Filings', 'ROC Filings'), ('Transfer Pricing', 'Transfer Pricing'), ('Bank Audit', 'Bank Audit')], max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Accounting', 'Accounting'), ('Analytics', 'Analytics'), ('Taxation', 'Taxation'), ('Software', 'Software'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
