# Generated by Django 5.2 on 2026-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ca_status',
            field=models.CharField(blank=True, choices=[('FOUNDATION', 'CA Foundation Cleared'), ('INTERMEDIATE', 'CA Intermediate'), ('ARTICLE_ONGOING', 'Articleship Ongoing'), ('ARTICLE_COMPLETED', 'Articleship Completed'), ('FINAL_APPEARED', 'CA Final Appeared / Not Cleared'), ('COMMERCE_GRAD', 'Commerce Graduate / Post-Graduate')], max_length=20, null=True, verbose_name='Current CA Status'),
        ),
    ]
