# Generated by Django 5.2.3 on 2026-03-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short summary highlighting experience or academic goals.', null=True, verbose_name='Professional Summary / Objective')),
                ('cv_template_preference', models.CharField(choices=[('professional', 'Format A: Professional (Experience-Focused)'), ('academic', 'Format B: Fresher (Academic-Focused)')], default='professional', max_length=20, verbose_name='CV Template Format')),
                ('icai_reg_num', models.CharField(blank=True, max_length=20, verbose_name='ICAI Registration Number')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='Languages Known')),
                ('availability', models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate'), ('15_DAYS', '15 Days'), ('30_DAYS', '30 Days'), ('NOTICE', 'Notice Period')], max_length=20)),
                ('foundation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('foundation_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('inter_attempts_g1', models.PositiveIntegerField(blank=True, null=True)),
                ('inter_attempts_g2', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_articleship_city', models.CharField(blank=True, max_length=100)),
                ('preferred_industries', models.JSONField(blank=True, default=list, verbose_name='Preferred Industries')),
                ('industry_preference', models.CharField(blank=True, choices=[('MANUFACTURING', 'Manufacturing'), ('REAL_ESTATE', 'Real Estate'), ('IT_STARTUP', 'IT / Startups'), ('NBFC_BANK', 'NBFC / Banks'), ('HOSPITAL_NGO', 'Hospitals / NGOs'), ('RETAIL', 'Trading & Retail')], max_length=50)),
                ('current_firm_city', models.CharField(blank=True, max_length=100)),
                ('articleship_start_date', models.DateField(blank=True, null=True)),
                ('seeking_type', models.CharField(blank=True, choices=[('TRANSFER', 'Articleship Transfer'), ('INDUSTRIAL', 'Industrial Training')], max_length=20)),
                ('is_confidential_mode', models.BooleanField(default=True)),
                ('articleship_end_date', models.DateField(blank=True, null=True)),
                ('domain_exposure', models.JSONField(blank=True, help_text='Domain-wise exposure with proficiency', null=True)),
                ('preferred_job_roles', models.CharField(blank=True, choices=[('AUDIT_EXEC', 'Audit Executive'), ('ACCOUNTS_EXEC', 'Accounts Executive'), ('TAX_EXEC', 'Tax Executive'), ('GST_ANALYST', 'GST Analyst'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('MIS_EXEC', 'MIS Executive'), ('FINANCE_ANALYST', 'Finance Analyst'), ('VIRTUAL_ACCOUNTANT', 'Virtual Accountant'), ('CLIENT_REL_EXEC', 'Client Relationship Executive')], max_length=50)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('CONTRACT', 'Contractual'), ('FREELANCE', 'Freelance'), ('PROJECT', 'Project-based')], max_length=20)),
                ('final_group_appeared', models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('BOTH', 'Both')], max_length=10)),
                ('final_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('career_preference', models.CharField(blank=True, choices=[('CORPORATE_JOB', 'Corporate Job'), ('PRACTICE_SUPPORT', 'Practice Support'), ('VIRTUAL_ROLE', 'Virtual / Remote Role')], max_length=30)),
                ('study_status', models.CharField(blank=True, choices=[('STUDY_WORK', 'Studying + Working'), ('PAUSED', 'Temporarily Paused Attempts')], max_length=20)),
                ('articleship_completion_cert', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('experience_proof', models.FileField(blank=True, null=True, upload_to='experience_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('preferred_domains', models.ManyToManyField(blank=True, related_name='candidates_preferred', to='adminpanel.domain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title (e.g., Transfer Pricing Course, Gold Medalist)')),
                ('issuer_organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Issuing Organization')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('WORKING', 'Working Knowledge'), ('INDEPENDENT', 'Independent Handling')], default='BEGINNER', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.manageskill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='software_skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', through='candidates.CandidateSkill', to='adminpanel.manageskill'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=150, verbose_name='Degree / Qualification (e.g., B.Com, HSC)')),
                ('institution_board', models.CharField(max_length=255, verbose_name='Institution / Board')),
                ('passing_year', models.CharField(max_length=20, verbose_name='Year of Passing')),
                ('score_percentage', models.CharField(max_length=50, verbose_name='Marks / Percentage / CGPA')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks (e.g., First Attempt)')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Job Title / Designation')),
                ('company_firm_name', models.CharField(max_length=255, verbose_name='Company / Firm Name')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_currently_working', models.BooleanField(default=False, verbose_name='Currently Working Here')),
                ('description', models.TextField(help_text='Write bullet points summarizing your work.', verbose_name='Job Description / Roles & Responsibilities')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
